export const mockStocks = [
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    price: 178.72,
    change: 2.34,
    changePercent: 1.33,
    volume: "52.3M",
    marketCap: "2.78T",
    high: 180.12,
    low: 176.45,
    open: 177.25,
  },
  {
    symbol: "MSFT",
    name: "Microsoft Corporation",
    price: 378.91,
    change: -1.23,
    changePercent: -0.32,
    volume: "18.7M",
    marketCap: "2.81T",
    high: 381.5,
    low: 376.2,
    open: 380.0,
  },
  {
    symbol: "GOOGL",
    name: "Alphabet Inc.",
    price: 141.8,
    change: 3.45,
    changePercent: 2.49,
    volume: "24.1M",
    marketCap: "1.79T",
    high: 143.2,
    low: 139.5,
    open: 140.0,
  },
  {
    symbol: "TSLA",
    name: "Tesla, Inc.",
    price: 248.5,
    change: -5.67,
    changePercent: -2.23,
    volume: "98.4M",
    marketCap: "789B",
    high: 255.0,
    low: 245.0,
    open: 253.0,
  },
  {
    symbol: "NVDA",
    name: "NVIDIA Corporation",
    price: 495.22,
    change: 12.45,
    changePercent: 2.58,
    volume: "45.6M",
    marketCap: "1.22T",
    high: 498.0,
    low: 485.0,
    open: 488.0,
  },
  {
    symbol: "AMZN",
    name: "Amazon.com, Inc.",
    price: 178.25,
    change: 1.89,
    changePercent: 1.07,
    volume: "32.8M",
    marketCap: "1.84T",
    high: 180.0,
    low: 176.5,
    open: 177.0,
  },
]

export const mockNews = [
  {
    id: 1,
    title: "Apple Announces Record Q4 Earnings, Stock Surges",
    source: "Bloomberg",
    time: "2 hours ago",
    sentiment: "positive",
    sentimentScore: 0.85,
    summary: "Apple reported better-than-expected earnings for Q4, driven by strong iPhone and services revenue.",
  },
  {
    id: 2,
    title: "Tesla Faces Production Challenges in European Market",
    source: "Reuters",
    time: "4 hours ago",
    sentiment: "negative",
    sentimentScore: -0.42,
    summary: "Tesla's Berlin factory is experiencing delays due to supply chain issues affecting production targets.",
  },
  {
    id: 3,
    title: "NVIDIA's AI Chips Continue to Dominate the Market",
    source: "TechCrunch",
    time: "6 hours ago",
    sentiment: "positive",
    sentimentScore: 0.78,
    summary:
      "NVIDIA maintains its lead in AI chip market with new partnerships and increased demand from cloud providers.",
  },
  {
    id: 4,
    title: "Microsoft Cloud Revenue Exceeds Analyst Expectations",
    source: "CNBC",
    time: "8 hours ago",
    sentiment: "positive",
    sentimentScore: 0.65,
    summary: "Azure cloud services growth accelerates as enterprises continue digital transformation initiatives.",
  },
  {
    id: 5,
    title: "Amazon Expands Same-Day Delivery to More Cities",
    source: "WSJ",
    time: "10 hours ago",
    sentiment: "neutral",
    sentimentScore: 0.15,
    summary: "Amazon announces expansion of its same-day delivery network to 15 additional metropolitan areas.",
  },
]

export const mockFinancials = {
  revenue: [
    { quarter: "Q1 2023", value: 94.8 },
    { quarter: "Q2 2023", value: 81.8 },
    { quarter: "Q3 2023", value: 89.5 },
    { quarter: "Q4 2023", value: 119.6 },
    { quarter: "Q1 2024", value: 90.8 },
    { quarter: "Q2 2024", value: 85.8 },
  ],
  earnings: [
    { quarter: "Q1 2023", value: 1.52 },
    { quarter: "Q2 2023", value: 1.26 },
    { quarter: "Q3 2023", value: 1.46 },
    { quarter: "Q4 2023", value: 2.18 },
    { quarter: "Q1 2024", value: 1.53 },
    { quarter: "Q2 2024", value: 1.4 },
  ],
}

export const mockPredictions = [
  {
    model: "Gemini",
    prediction: "Buy",
    confidence: 78,
    targetPrice: 195.0,
    reasoning:
      "Strong fundamentals, consistent revenue growth, and positive market sentiment support upside potential.",
  },
  {
    model: "GPT-4",
    prediction: "Hold",
    confidence: 65,
    targetPrice: 182.0,
    reasoning:
      "Current valuation is fair. Waiting for next earnings report before making significant position changes.",
  },
  {
    model: "Grok",
    prediction: "Buy",
    confidence: 72,
    targetPrice: 190.0,
    reasoning: "Technical indicators show bullish momentum. Support levels are strong with low downside risk.",
  },
]

export const mockChartData = [
  { date: "Jan", price: 165.25 },
  { date: "Feb", price: 168.5 },
  { date: "Mar", price: 172.35 },
  { date: "Apr", price: 169.8 },
  { date: "May", price: 175.45 },
  { date: "Jun", price: 178.9 },
  { date: "Jul", price: 182.3 },
  { date: "Aug", price: 176.55 },
  { date: "Sep", price: 171.2 },
  { date: "Oct", price: 174.85 },
  { date: "Nov", price: 178.72 },
]
